/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TanksIndexImport } from './routes/tanks/index'
import { Route as TanksTankIdDetailImport } from './routes/tanks/$tankId/detail'
import { Route as TanksTankIdFermentationsNewImport } from './routes/tanks/$tankId/fermentations/new'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TanksIndexRoute = TanksIndexImport.update({
  id: '/tanks/',
  path: '/tanks/',
  getParentRoute: () => rootRoute,
} as any)

const TanksTankIdDetailRoute = TanksTankIdDetailImport.update({
  id: '/tanks/$tankId/detail',
  path: '/tanks/$tankId/detail',
  getParentRoute: () => rootRoute,
} as any)

const TanksTankIdFermentationsNewRoute =
  TanksTankIdFermentationsNewImport.update({
    id: '/tanks/$tankId/fermentations/new',
    path: '/tanks/$tankId/fermentations/new',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tanks/': {
      id: '/tanks/'
      path: '/tanks'
      fullPath: '/tanks'
      preLoaderRoute: typeof TanksIndexImport
      parentRoute: typeof rootRoute
    }
    '/tanks/$tankId/detail': {
      id: '/tanks/$tankId/detail'
      path: '/tanks/$tankId/detail'
      fullPath: '/tanks/$tankId/detail'
      preLoaderRoute: typeof TanksTankIdDetailImport
      parentRoute: typeof rootRoute
    }
    '/tanks/$tankId/fermentations/new': {
      id: '/tanks/$tankId/fermentations/new'
      path: '/tanks/$tankId/fermentations/new'
      fullPath: '/tanks/$tankId/fermentations/new'
      preLoaderRoute: typeof TanksTankIdFermentationsNewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tanks': typeof TanksIndexRoute
  '/tanks/$tankId/detail': typeof TanksTankIdDetailRoute
  '/tanks/$tankId/fermentations/new': typeof TanksTankIdFermentationsNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tanks': typeof TanksIndexRoute
  '/tanks/$tankId/detail': typeof TanksTankIdDetailRoute
  '/tanks/$tankId/fermentations/new': typeof TanksTankIdFermentationsNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/tanks/': typeof TanksIndexRoute
  '/tanks/$tankId/detail': typeof TanksTankIdDetailRoute
  '/tanks/$tankId/fermentations/new': typeof TanksTankIdFermentationsNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tanks'
    | '/tanks/$tankId/detail'
    | '/tanks/$tankId/fermentations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tanks'
    | '/tanks/$tankId/detail'
    | '/tanks/$tankId/fermentations/new'
  id:
    | '__root__'
    | '/'
    | '/tanks/'
    | '/tanks/$tankId/detail'
    | '/tanks/$tankId/fermentations/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TanksIndexRoute: typeof TanksIndexRoute
  TanksTankIdDetailRoute: typeof TanksTankIdDetailRoute
  TanksTankIdFermentationsNewRoute: typeof TanksTankIdFermentationsNewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TanksIndexRoute: TanksIndexRoute,
  TanksTankIdDetailRoute: TanksTankIdDetailRoute,
  TanksTankIdFermentationsNewRoute: TanksTankIdFermentationsNewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/tanks/",
        "/tanks/$tankId/detail",
        "/tanks/$tankId/fermentations/new"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/tanks/": {
      "filePath": "tanks/index.tsx"
    },
    "/tanks/$tankId/detail": {
      "filePath": "tanks/$tankId/detail.tsx"
    },
    "/tanks/$tankId/fermentations/new": {
      "filePath": "tanks/$tankId/fermentations/new.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
